%YAML:1.0

cam0_calib: "/home/bo/MonoLidarMapping/src/mono_lidar_mapping/config/hk_cam00.yaml"
cam1_calib: "/home/bo/MonoLidarMapping/src/mono_lidar_mapping/config/hk_cam01.yaml"
image0_topic: "/left_camera_pointgrey/image_color"
image_width: 1920
image_height: 1200

min_pnp_loop_num: 10
min_brief_loop_num: 10
min_orb_loop_num: 20
use_orb: 0
skip_time: 1.0
skip_dis: 0.5
skip_cnt: 0
loop_search_time: 0.5
loop_search_gap: 200
debug_image: 0
angle_threshold: 4
trans_threshold: 1
skip_loop_time: 1.0
skip_loop_dis: 0.5
image_crop: 256
