%YAML:1.0

cam0_calib: "/home/bo/auto-calib/src/auto_calib/config/cam00.yaml"
cam1_calib: "/home/bo/auto-calib/src/auto_calib/config/cam01.yaml"

image_width: 1241
image_height: 376

min_pnp_loop_num: 5
min_brief_loop_num: 20
min_orb_loop_num: 20
skip_time: 0.2
skip_dis: 0.5
skip_cnt: 0
loop_search_time: 0.3
loop_search_gap: 50
debug_image: 1


