%YAML:1.0

cam0_calib: "/home/bo/lmono/src/mono_lidar_mapping/config/kitti00_cam.yaml"
cam1_calib: "/home/bo/lmono/src/mono_lidar_mapping/config/kitti_cam01.yaml"

image_width: 1241
image_height: 376
image0_topic: "/image_left"
skip_dis: 0
filter_size: 11
kernel_type: FULL
blur_type: bilateral #or  guassian 
kernel_size: 5
save_map: 1
